### PR TITLE
MMDP-428  Manage community dropdown options

### PR DESCRIPTION
**Pull request by jomasim**
**What does this PR do?**

- This PR implements CRUD operations for the beneficiary type dropdown

**description of Task to be completed?**
- [x] implement create/add a new community dropdown option
- [x] implement edit community dropdown option
- [x] implement list community dropdown options
- [x] implement delete community dropdown option

**How should this be manually tested?**
- Clone the project 
```
$ git clone https://github.com/andela/mmdp_site.git
```
- Checkout fix bug branch 
```
$ git checkout ft-community-dropdown-MMDP-428
```
- Run application
```
$ yarn run dev-server
```

- On your browser navigate to /dropdowns/community from the CMS
- Click add more dropdowns and fill the fields

**Any background context you want to provide?**

None

**What are the relevant Jira issues?**

[MMDP-428](https://viisaus.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=MMDP&view=planning&selectedIssue=MMDP-428)

**Screenshots (if appropriate)**
Screenshot 2019-04-03 at 06 57 55

**Questions:**

If something is unclear or you want some questions to be addressed by your peers, mention them here

### CODE REVIEW

**Comment by Ruiru11** [comment]
I get this when I run you frontend tests 
image

**Comment by jomasim** [comment]
> I get this when I run you frontend tests
> image

@Ruiru11  thanks on the feedback let me check that

**Comment by jomasim** [comment]
> > I get this when I run you frontend tests
> > image
> 
> @Ruiru11 thanks on the feedback let me check that

@Ruiru11 the error on the test is fixed check again

**Comment by Ruiru11** [comment]
feedback worked on good work

**Pull request merged**
