### PR TITLE
MMDP-0000:fix the edit stakeholders feature

### PR DESCRIPTION
**Pull request by fgkinus**
**What does this PR do?**

It fixes the update stakeholder details feature while implementing stakeholder feedback from the predemo

**description of Task to be completed?**
- fix email field sizing in relation to the text fields
- add edit-stakeholder functionality
- add unit tests for the front end
- fix label and placeholder messages
- add partnerships validation to add a partnership and partnership at a time
- add coloured tabs at the top of the page

**How should this be manually tested?**
- `git fetch`
- `git checkout bg-fix-edit-feature`
- Navigate to `http://localhost:1234/stakeholder-directory/add-basic-information`

**What are the relevant Jira issues?**

[MMDP-000](https://viisaus.atlassian.net/browse/MMDP-000)

**Screenshots (if appropriate)**
- add coloured tabs at the top of the page
image

- fix height of email fields
image

- add organisation name field to beneficiaries CSV
image

- add validation for beneficiary types to prevent redundant entries
image

### CODE REVIEW

**Comment by eduhmik** [comment]
Hey @fgkinus, great job!
I, however, realized the following issues
When adding a new stakeholder, the thematic pillars dropdown does not list the available dropdowns
Screenshot 2019-05-09 at 10 13 49

Screenshot 2019-05-09 at 10 20 24


When editing the stakeholder's feature, the local government, local community and ward fields do not populate with the prefilled info.
Screenshot 2019-05-09 at 10 20 24

**Comment by Ruiru11** [comment]
Good work Francis but I am not able to edit this 
image

Second, I get this console warning
image

**Comment by fgkinus** [comment]
> Good work Francis but I am not able to edit this
> image
> 

> Second, I get this console warning
> image

Hi @Ruiru11 .The Console warning is generated from the package used to display the date selector. When the prop for positioning the calendar icon provided is changed to left, the error is removed but then the component does not match the mockups. The error does not seem to break the functionality of the package of the error however. I am sure once the package author fixes the bug hten the bug will be removed

**Comment by Ruiru11** [comment]
Thanks for the clarification I have actually confirmed that.

**Pull request merged**
