### PR TITLE
MMDP-582 Implement changing text from organization to organisation

### PR DESCRIPTION
**Pull request by missvicki**
**What does this PR do?**

- Change the text "Organization" to "Organisation" in all occurences

**How should this be manually tested?**

- `git fetch`
- `git checkout bg-fix-organisation-naming-MMDP-582`
- `yarn run dev-server`
- navigate to `/manage/dropdowns` and click on Organisation Type dropdown

**What are the relevant Jira issues?**

[MMDP-582](https://viisaus.atlassian.net/browse/MMDP-582)

**Screenshots (if appropriate)**
Screenshot 2019-05-23 at 10 45 37

### CODE REVIEW

**Comment by eduhmik** [comment]
The PR title says changing the text from organisation to organisation, maybe you might consider making changes

**Comment by missvicki** [comment]
> The PR title says changing the text from organisation to organisation, maybe you might consider making changes

**Comment by missvicki** [comment]
> The PR title says changing the text from organisation to organisation, maybe you might consider making changes

thank you for noticing this. i've revised it accordingly

**Comment by blackdevelopa** [comment]
LGTM

**Pull request merged**
